#!/usr/bin/env fish

set main_argv $argv

function __jj_new_branch
  read -d \t -a -l args
  set -l ticket $args[1]
  set -l name (string trim $args[2] | string lower | string replace -a ' ' "-" -- | string replace -a -r "[^\-0-9a-z]" "" --)
  set -l branchname "jeffs/$ticket/$name"
  jj bookmark create $main_argv $branchname
end

jira issue list -a (jira me) -s~"Closed" --raw | \
  jq -r '.[] | "\(.key)\t\(.fields.summary)"' | \
  fzf \
    --delimiter "\t" \
    --reverse \
    --preview="jira issue view {1}" | \
  __jj_new_branch
