#!/usr/bin/env -S usage fish
#USAGE flag "-t --tmp" help="Write the output file in /tmp"
#USAGE flag "-c --copy" help="Copy the output path to the clipboard"
#USAGE flag "-y --yoink" help="Pass the output path to yoink"
#USAGE flag "-o --output <output>" help="Use this output filename"
#USAGE flag "-m --mute" help="Remove audio from the output"
#USAGE flag "--crf <crf>" help="Set the video constant rate factor"
#USAGE flag "-e --epoch" help="Use the current Unix timestamp as the filename"
#USAGE arg "<files>..." help="Input video files to convert"

eval "set files $usage_files"

if test (count $files) -gt 1
  if test "$usage_copy" = true; or set -q usage_output
    echo "Only works with one file at a time, exiting" >&2
    exit 1
  end
end
if test "$usage_copy" = true; and not command -sq file-to-clipboard
  echo "No file-to-clipboard command, will not copy" >&2
  exit 1
end

for i in $files
  set -l ext (string split --right --max 1 '.' -- $i)[-1]
  set -l newname (basename $i "."$ext | string replace -r '\.[hx]265' '' )'.mp4'
  if test "$usage_epoch" = true
    set newname (date +%s).mp4
  end
  if set -q usage_output
    set newname "$usage_output"
  end
  if test "$usage_tmp" = true
    set newname /tmp/$newname
  end
  set -l audio_codec
  if test "$usage_mute" = true
    set audio_codec -an
  else
    set audio_codec -c:a aac
  end
  set -l crf_args
  if set -q usage_crf
    set crf_args -crf "$usage_crf"
  end

  ffmpeg -hide_banner -i $i -c:v libx264 $audio_codec -pix_fmt yuv420p -map_metadata -1 -vf "scale=ceil(iw/2)*2:ceil(ih/2)*2" $crf_args -y $newname
  set newname (readlink -f $newname)
  test "$usage_copy" = true; and file-to-clipboard $newname
  test "$usage_yoink" = true; and yoink $newname
  echo $newname
end
