#!/usr/bin/env fish
argparse -i "c/change=+" "r/ref=+" "N/dry-run" -- $argv

trap "exit 2" SIGINT

function pr_title_args --argument-names bookmark
  string match -grq "jeffs/(?<ticket>\w+-\d+)/(?<description>.*)" -- $bookmark; or return
  set description (string replace -a -- '-' ' ' $description)

  printf '[%s] %s' $ticket $description
end

set -l push_args
set -l bookmarks

set -q _flag_dry_run; and set dry_run "--dry-run"

if set -q _flag_change
  set -a push_args -N
  for rev in $_flag_change
    set -a push_args -c $rev
  end
  jj git push $dry_run $push_args &| read -z push_result
  echo $push_result

  string match -q -g --all --regex  "Add bookmark (?<bookmarks>.*)\*? to" $push_result
else
  if set -q _flag_ref
    set refs $_flag_ref
  else
    set refs "@"
  end

  for ref in $refs
    set -a bookmarks (jj log -r "heads(::$ref & bookmarks())" -T "bookmarks ++ '"\n"'" --no-graph | string replace '*' '' )
  end
end

for bookmark in $bookmarks
  jj bookmark track $bookmark@origin
  jj git push -b $bookmark
  echo (set_color --bold cyan)"Opening PR for $bookmark"(set_color reset)
  jj log -r "trunk()..$bookmark"

  set title (pr_title_args $bookmark)
  test -n "$title"; and set -p title --title


  gh pr create $dry_run -H $bookmark $title $argv
end
