lastChangelogVersion: 15.10.7
symbolPreset: nerd
theme: 
  dark: titanium
  light: light
setupVersion: 1
statusLine: 
  preset: custom
  leftSegments: 
    - model
    - mode
    - path
    - pr
    - session
    - subagents
  rightSegments: 
    - session_name
    - token_in
    - token_out
    - cache_read
    - cache_write
    - token_rate
    - cost
    - context_pct
    - context_total
    - time_spent
    - time
display: 
  showTokenUsage: true
task: 
  showResolvedModelBadge: true
modelRoles: 
  default: openrouter/openai/gpt-oss-120b:free
defaultThinkingLevel: auto
secrets: 
  enabled: true
github: 
  enabled: true
showHardwareCursor: false
tools: 
  discoveryMode: mcp-only
mcp: 
  discoveryMode: false
hideThinkingBlock: false