[template-aliases]
builtin_log_node = '''
coalesce(
  if(!self, label("elided", "~")),
  label(
    separate(" ",
      if(current_working_copy, "working_copy"),
      if(immutable, "immutable", "mutable"),
      if(self.contained_in("private_commits()::"), "private"),
      if(conflict, "conflicted"),
    ),
    coalesce(
      if(current_working_copy, "@"),
      if(immutable, "◆"),
      if(conflict, "×"),
      if(self.contained_in("private_commits()::"), "◍"),
      "○",
    )
  )
)
'''

[colors]
private = "yellow"
