"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

# Username, gpg key, and other per-machine settings are in ./conf.d/local.toml
[signing]
behavior = "own"
backend = "gpg"

[revsets]
log = 'present(@) | ancestors(immutable_heads().., 5) | present(trunk())'

[ui]
default-command = "log"
diff-editor = ":builtin"
diff-formatter = ":git" # required by `delta`
pager=["delta", "--pager", "less -FRX"] # Keeps output from the terminal after closing the pager

[diff]
tool = "delta"

[aliases]
a = ["abandon"]
d = ["describe"]
e = ["edit"]
g = ['git']
n = ["new"]
p = ["git", "push"]
rebase-all = ["rebase", "-s", "(::trunk())+ & mutable()", "--onto", "trunk()"]
s = ["show"]
# `jj stack <revset>` to include specific revs
stack = ["rebase", "--after", "trunk()", "--before", "closest_merge(@)", "--revisions"]

# `jj stage` to include the whole stack after the megamerge
stage = ["stack", "closest_merge(@)+:: ~ empty()"]

# `jj restack` to rebase your changes onto `trunk()`
restack = ["rebase", "--onto", "trunk()", "--source", "roots(trunk()..) & mutable()", "--simplify-parents"]

[revset-aliases]
'local_trunk()' = '''
latest(
  bookmarks(exact:"main") |
  bookmarks(exact:"master") |
  bookmarks(exact:"trunk") |
  root()
)
'''
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'
"closest_merge(to)" = "heads(::to & merges())"
'private_commits()' = "description(glob:'private:*') | bookmarks(glob:'private/*') | bookmarks(exact:'megamerge')"

[templates]
git_push_bookmark = '"jeffs/push/" ++ change_id.short()'

[template-aliases]
"format_timestamp(timestamp)" = """
if(timestamp.before("1 week ago"),
timestamp,
timestamp.ago()
)
"""

[colors]
tag = { fg = "magenta", italic = true }
tags = { fg = "magenta", italic = true }

[fsmonitor]
backend = "watchman"

[fsmonitor.watchman]
register-snapshot-trigger = true

[merge-tools.zed]
program = "zed"
diff-args = ["--diff", "$left", "$right"]

[merge-tools.ksdiff]
diff-invocation-mode = "file-by-file"
diff-args = ["--partial-changeset", "$left", "$right"]
merge-args = ["--merge", "--output", "$output", "--base", "$base", "$left", "$right"]

[git]
private-commits = "private_commits()"
colocate = true
write-change-id-header = true

[remotes.origin]
# Auto-track my prefixed bookmarks in all circumstances
auto-track-bookmarks = "glob:jeffs/*"

# These options allow for `jj diff` and `jj show` to clear the output from the terminal after closing the pager.
[[--scope]]
--when.commands = ["diff", "show"]

[--scope.ui]
pager = "delta"
