# These configs are things that I want on every machine I use
# Local configs should go in the ~/.config/mise/config.toml file
[tools]
"cargo:cargo-generate" = "latest"
"cargo:lucky_commit" = "latest"
"cargo:sd" = "latest"
"cargo:spurdify" = "latest"
cargo-binstall = "latest"
cosign = "latest"
rust = "stable"
slsa-verifier = "latest"
usage = "latest"
watchexec = "latest"
"cargo:diffedit3" = "latest"


[settings]
jobs = 8
experimental = true
lockfile = true
# Docker makes a _far_ better portable postgres setup
disable_tools = ["postgres"]

[settings.npm]
bun = true
